# Dependencies
markdown:         redcarpet
pygments:         true

# Markdown
redcarpet:
  extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]


# Permalinks
permalink:        /:year/:month/:day/:title/index.html

title:            Salathe

author:
  name:           'Peter Cowburn'
  url:            http://cowburn.info

github:
  repo:           https://github.com/salathe/cowburn.info/
